plugins:
  paved_email_banner_enabled:
    default: true
  paved_email_banner_api_key:
    default: ""
  paved_email_banner_include_email:
    default: true
  paved_email_banner_selective_placement:
    default: false
